### ISSUE TITLE
AUR package fails to install. "No module named pip"?

### ISSUE THREAD

**Issue by Pistrie** [Spoons/rmm#11]
**Description**
When installing the AUR package it fails with the following message:
<details>
<summary markdown="span">Error log</summary>

```
/usr/lib/python3.10/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
  warnings.warn(msg, warning_class)
/usr/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
/usr/bin/python: No module named pip
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpgrhh0hkb', '--quiet', 'pbr']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sylvester/.cache/paru/clone/rmm-git/src/rmm-git/setup.py", line 3, in <module>
    setup(setup_requires=["pbr"], pbr=True)
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 874, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
    dist = best[req.key] = env.best_match(
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
    return installer(requirement)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 944, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/usr/lib/python3.10/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
    raise DistutilsError(str(e)) from e
distutils.errors.DistutilsError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpgrhh0hkb', '--quiet', 'pbr']' returned non-zero exit status 1.
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'rmm-git-1.0.11-1': 
error: packages failed to build: rmm-git-1.0.11-1
```

</details>

**Reproduction**
1. run `paru -S rmm-git`
2. go through the installation and wait for the error to occur

**Info**
OS: Garuda Linux

**Comment by Spoons** [comment]
I don't know much about Garuda but I'll take a look.

Do you have 'python-pip' installed? It looks like I need to add that as an explicit dependency.

**Comment by Spoons** [comment]
I pushed out an updated PKGBUILD to the aur. It should work for you now. Let me know if it doesn't.

**Comment by Pistrie** [comment]
It installs now :)

**Comment by Spoons** [comment]
Perfect!
