### ISSUE TITLE
FileNotFoundError on Ubuntu on sync or update

### ISSUE THREAD

**Issue by stasalcatraz** [Spoons/rmm#28]
Trying to install (or update) mod and get error

> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/rmm-y4q05ss4/Steam/SteamApps/workshop/content/294100'

According to the console output, the file was successfully downloaded to `/tmp/rmm-y4q05ss4/Steam/steamapps/workshop/content/294100/1356838246`
RimWorld is bought on gog.com, not steam, but other steam games are present at `~/.steam/root/steamapps/workshop/...` 
Here is the full console output:
```console
$ rmm sync uugggg.sharetheload
  no  name            author
----  --------------  --------
   1  Share The Load  Uuugggg
Packages to install (eg: 2 or 1-3)
1
Package(s): 
Share The Load by Uuugggg 

will be installed.
ln: failed to create symbolic link '/tmp/rmm-y4q05ss4/.steam/root': No such file or directory
ln: failed to create symbolic link '/tmp/rmm-y4q05ss4/.steam/steam': No such file or directory
Redirecting stderr to '/tmp/rmm-y4q05ss4/Steam/logs/stderr.txt'
Logging directory: '/tmp/rmm-y4q05ss4/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1702079268
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Downloading item 1356838246 ...
Success. Downloaded item 1356838246 to "/tmp/rmm-y4q05ss4/Steam/steamapps/workshop/content/294100/1356838246" (656922 bytes) Traceback (most recent call last):
  File "/home/alcatraz/.local/bin/rmm", line 8, in <module>
    sys.exit(run())
  File "/home/alcatraz/.local/lib/python3.10/site-packages/rmm/cli.py", line 569, in run
    globals()[command](sys.argv, manager)
  File "/home/alcatraz/.local/lib/python3.10/site-packages/rmm/cli.py", line 98, in wrapper_func
    func(*args, **kwargs)
  File "/home/alcatraz/.local/lib/python3.10/site-packages/rmm/cli.py", line 321, in sync
    manager.sync_mods(queue)
  File "/home/alcatraz/.local/lib/python3.10/site-packages/rmm/manager.py", line 72, in sync_mods
    steam_mods, steam_cache_path = SteamDownloader.download(
  File "/home/alcatraz/.local/lib/python3.10/site-packages/rmm/steam.py", line 111, in download
    return (ModFolder.read(mod_path), mod_path)
  File "/home/alcatraz/.local/lib/python3.10/site-packages/rmm/mod.py", line 157, in read
    p.map(
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 478, in _map_async
    iterable = list(iterable)
  File "/usr/lib/python3.10/pathlib.py", line 1017, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/rmm-y4q05ss4/Steam/SteamApps/workshop/content/294100'
```

**Comment by pswsm** [comment]
Same error as #16 , safe to say that the workaround dev made did not work effectively since I also had that error.

I've made a PR so it should be patched once it's merged
