### ISSUE TITLE
`name 'manager' is not defined`

### ISSUE THREAD

**Issue by Lippiece** [Spoons/rmm#30]
This happens when I use `rmm sort`.

```
╰─ rmm sort
Downloading rules file

Traceback (most recent call last):
  File "/usr/bin/rmm", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/usr/lib/python3.11/site-packages/rmm/cli.py", line 569, in run
    globals()[command](sys.argv, manager)
  File "/usr/lib/python3.11/site-packages/rmm/cli.py", line 98, in wrapper_func
    func(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/rmm/cli.py", line 367, in sort
    manager.modsconfig.autosort(manager.installed_mods(), manager.config)
  File "/usr/lib/python3.11/site-packages/rmm/modsconfig.py", line 113, in autosort
    manager.Manager(config).sync_mods([Mod(steamid=1847679158)])
    ^^^^^^^
NameError: name 'manager' is not defined
```

**Comment by stasalcatraz** [comment]
The same error.
